config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :punch_setting

  resources :punch_schedules do
    member do
      post :cancel
    end
  end

  # Sidekiq Admin Web UI
  require "sidekiq/web"
  require "sidekiq/cron/web"
  authenticate :user, ->(user) { user.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  root "home#index"
end

app/models/punch_setting.rb
class PunchSetting < ApplicationRecord
  belongs_to :user

  validate :work_time_range

  enum status: {
    disable: 0,
    enable: 1
  }

  enum geo_status: {
    geo_disable: 0,
    geo_enable: 1
  }

  def mask_id_serial
    return "" if id_serial.blank?
    id_serial.dup.tap { |m| m[2..4] = "***" }
  end

  private

  def work_time_range
    work_time_range = Time.zone.strptime(end_work_time, '%H%M').to_i - Time.zone.strptime(start_work_time, '%H%M').to_i
    if work_time_range < 8.5.hours.to_i
      errors.add(:end_work_time, "時間區間要大於 8.5 小時，實際工時 7.5小時")
    end
  end
end

# == Schema Information
#
# Table name: punch_settings
#
#  id                            :bigint           not null, primary key
#  end_work_padding_percentage   :integer          default(0), not null
#  end_work_time                 :string           not null
#  geo_latitude                  :decimal(10, 6)   default(0.0), not null
#  geo_longitude                 :decimal(10, 6)   default(0.0), not null
#  geo_status                    :integer          default(0), not null
#  id_serial                     :string           not null
#  start_work_padding_percentage :integer          default(0), not null
#  start_work_time               :string           not null
#  status                        :integer          default("disable"), not null
#  uid                           :string           not null
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  user_id                       :integer          not null
#

app/controllers/punch_settings_controller.rb
class PunchSettingsController < ApplicationController
  layout "dashboard"

  before_action :authenticate_user!

  def new
    @punch_setting = current_user.build_punch_setting
  end

  def create
    @punch_setting = current_user.build_punch_setting(punch_setting_params)

    if @punch_setting.save
      redirect_to punch_setting_path
    else
      render :new
    end
  end

  def edit
    @punch_setting = current_user.punch_setting
  end

  def update
    @punch_setting = current_user.punch_setting

    if @punch_setting.update(punch_setting_params)
      redirect_to punch_setting_path
    else
      render :edit
    end
  end

  def show
    @punch_setting = current_user.punch_setting
    @punch_schedules = current_user.punch_schedules.order(id: :asc)
    @punch_schedules_list = current_user.punch_schedules.order(id: :desc).paginate(page: params[:page], per_page: 12)
  end

  private

  def punch_setting_params
    params.require(:punch_setting).permit(:uid, :id_serial, :start_work_time, :start_work_padding_percentage, :end_work_time, :end_work_padding_percentage, :status, :geo_latitude, :geo_longitude, :geo_status)
  end
end

app/helpers/punch_settings_helper.rb
module PunchSettingsHelper
  # 早晚標籤
  def render_timeline_badge(time_line)
    klass = time_line == "AM" ? "badge bg-info" : "badge bg-warning text-dark"
    tag.span(time_line, class: klass)
  end

  # 執行結果標籤
  def render_status_tag(punch_schedule)
    klass = case punch_schedule.status
            when "successed"
              "badge bg-success"
            when "failed"
              "badge bg-danger"
            when "cancel"
              "badge bg-warning"
            else
              "badge bg-secondary"
            end
    tag.span(I18n.t("enum.punch_schedule.status.#{punch_schedule.status}"), class: klass)
  end

  # 開關狀態標籤
  def render_state_class(status)
    klass = case status
            when 0
              "badge bg-danger"
            when 1
              "badge bg-success"
            end
  end

  # 壓縮時間，方便畫線(2021/09/12 -> 912)
  def render_compression_time_array(punch_schedules)
    time_array = punch_schedules.pluck(:perform_at_unixtime)
    min_time_array = time_array.map do |time|
      return 0 if time.blank?
      (Time.zone.at(time).strftime("%H") + Time.zone.at(time).strftime("%M")).to_i
    end

    min_time_array.to_s.html_safe
  end

  # 平均上下班於
  def render_time_average(punch_schedules)
    return "00:00" if punch_schedules.blank?
    time_array = punch_schedules.pluck(:perform_at_unixtime)
    hour_array = time_array.map do |time|
      Time.zone.at(time).strftime("%H").to_i
    end
    sec_array = time_array.map do |time|
      Time.zone.at(time).strftime("%M").to_i
    end

    hour_text = (hour_array.sum / punch_schedules.size).to_s.rjust(2, "0")
    sec_text = (sec_array.sum / punch_schedules.size).to_s.rjust(2, "0")

    "#{hour_text}:#{sec_text}"
  end

  # 日期陣列
  def render_date_array(punch_schedules)
    perform_at_array = punch_schedules.pluck(:perform_at_unixtime)
    array = []
    perform_at_array.sort.each do |unixtime|
      array << Time.at(unixtime).strftime("%m/%d").to_s
    end
    array.to_s.html_safe
  end

  def render_this_month_daka_percentage(punch_schedules, month)
    punch_schedules.size * 100  / this_month_business_days(month.to_i)
  end
end

app/views/punch_settings/_form.html.erb
<%= simple_form_for @punch_setting, url: punch_setting_path do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :uid, label: "棉花糖 HR 登入系統帳號", required: true %>
    </div>
    <div class="col-md-6">
      <%= f.input :id_serial, label: "棉花糖 HR 登入系統密碼", required: true %>
    </div>
    <div class="col-xl-6">
      <h5 class="">打卡時間</h5>
      <p>如果希望早上 9 點 30分打卡，請輸入 0930</p>
      <p>為 24H 制，請輸入全數字</p>
      <hr>
      <%= f.input :start_work_time, label: "上班打卡時間" %>
      <%= f.input :end_work_time, label: "下班打卡時間" %>
    </div>
    <div class="col-xl-6">
      <h5 class="">飄移分鐘數</h5>
      <p>打卡時間為 0930，輸入 20，則會在 0930~0950 之間隨機打卡</p>
      <p>接受正負值，負值則是提前</p>
      <hr>
      <%= f.input :start_work_padding_percentage, label: "上班打卡時間飄移分鐘數" %>
      <%= f.input :end_work_padding_percentage, label: "下班打卡時間飄移分鐘數" %>
    </div>
    <div class="col-xl-6">
      <%= f.input :geo_latitude, label: "經度 (Latitude)", readonly: true %>
    </div>
    <div class="col-xl-6">
      <%= f.input :geo_longitude, label: "緯度 (Longitude)", readonly: true %>
    </div>
    <div class="col-xl-6">
      <div id='map' class="mb-4"></div>
    </div>
    <div class="col-xl-6">
      <div class="form-group">
        <label class="decimal optional" for="punch_setting_address">地址</label>
        <div class="input-group">
          <input id="address" type="text" class="form-control" placeholder="輸入地址取得經緯度">
          <button class="btn btn-success" type="button" id="address_search">查詢</button>
        </div>
      </div>
      <div class="form-check form-switch pl-2">
        <%= f.input :geo_status, as: :boolean, checked_value: 'geo_enable',unchecked_value: 'geo_disable', label: "加入GPS定位" %>
        <%= f.input :status, as: :boolean, checked_value: 'enable',unchecked_value: 'disable', label: "服務狀態開關" %>
      </div>
      <%= f.button :submit, "提交", class: "btn btn-success w-100" %>
    </div>
  </div>
<% end %>

app/views/punch_settings/_my_settings.html.erb
<% if defined?(table_type) && table_type == "row_column" %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">UID</th>
        <th scope="col">ID Serial</th>
        <th scope="col">開始工作時間</th>
        <th scope="col">開始工作飄移分鐘數</th>
        <th scope="col">結束工作時間</th>
        <th scope="col">結束飄移分鐘數</th>
        <th scope="col">開啟服務狀態</th>
        <th scope="col">開啟GPS定位</th>
        <th scope="col">#</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"><%= punch_setting.uid %></th>
        <th scope="row"><%= punch_setting.mask_id_serial %></th>
        <th scope="row"><%= punch_setting.start_work_time %></th>
        <th scope="row"><%= punch_setting.start_work_padding_percentage %></th>
        <th scope="row"><%= punch_setting.end_work_time %></th>
        <th scope="row"><%= punch_setting.end_work_padding_percentage %></th>
        <th scope="row"><%= t("enum.punch_setting.status.#{punch_setting.status}") %></th>
        <th scope="row"><%= t("enum.punch_setting.status.#{punch_setting.geo_status}") %></th>
        <th scope="row"><%= link_to("Edit", edit_punch_setting_path, class: "btn btn-sm btn-primary") %></th>
      </tr>
    </tbody>
  </table>
<% else %>
  <table class="table table-striped table-bordered">
    <colgroup>
      <col style="width: 200px;">
      <col style="">
    </colgroup>
    <tbody>
      <tr>
        <th>UID</th>
        <td class="text-left"><%= punch_setting.uid %></td>
      </tr>
      <tr>
        <th>ID Serial</th>
        <td class="text-left"><%= punch_setting.mask_id_serial %></td>
      </tr>
      <tr>
        <th>開始工作時間</th>
        <td class="text-left"><%= punch_setting.start_work_time %></td>
      </tr>
      <tr>
        <th>開始工作飄移分鐘數</th>
        <td class="text-left"><%= punch_setting.start_work_padding_percentage %></td>
      </tr>
      <tr>
        <th>結束工作時間</th>
        <td class="text-left"><%= punch_setting.end_work_time %></td>
      </tr>
      <tr>
        <th>結束飄移分鐘數</th>
        <td class="text-left"><%= punch_setting.end_work_padding_percentage %></td>
      </tr>
      <tr>
        <th>開啟服務狀態</th>
        <td class="text-left">
          <span class="<%= render_state_class(PunchSetting.statuses[punch_setting.status]) %>">
            <%= I18n.t("enum.punch_setting.status.#{punch_setting.status}") %>
          </span>
        </td>
      </tr>
      <tr>
        <th>開啟GPS定位</th>
        <td class="text-left">
          <span class="<%= render_state_class(PunchSetting.geo_statuses[punch_setting.geo_status]) %>">
            <%= I18n.t("enum.punch_setting.status.#{punch_setting.geo_status}") %>
          </span>
        </td>
      </tr>
      <tr>
        <th>操作</th>
        <td class="text-left"><%= link_to("修改", edit_punch_setting_path, class: "btn btn-sm btn-primary") %></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/punch_settings/edit.html.erb
<%= render "form" %>

app/views/punch_settings/new.html.erb
<%= render "form" %>

app/views/punch_settings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h2>我的打卡設定</h2>
        <small><strong><%= Date.today.workday? ? "西部世界工作日！" : "非工日，你還上來調整設定！" %></strong></small>
      </div>
      <div class="card-body">
        <% if @punch_setting.blank? %>
          <%= link_to("New", new_punch_setting_path) %>
        <% else %>
          <%= render partial: "my_settings", locals: { punch_setting: @punch_setting } %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card support-bar overflow-hidden">
      <div class="card-body pb-0">
        <h2 class="m-0"><%= render_this_month_daka_percentage(@punch_schedules.AM.successed.this_month, Time.current.month)  %>%</h2>
        <span class="text-primary"><%= Time.current.month %>月上班成功打卡率</span>
        <p class="text-primary"><%= Time.current.month %>月上班成功打卡次數(<%= @punch_schedules.AM.successed.this_month.size %>)</p>
        <!-- <p class="mb-3 mt-3">Number of conversions divided by the total visitors. </p> -->
      </div>
      <div id="support-chart"></div>
      <div class="card-footer border-0 bg-primary text-white background-pattern-white">
        <div class="row text-center">
          <%# 此處調用 month_at(month) 疑似 n+1 %>
          <% 4.times do |time| %>
            <% month = Time.current.month + (time - 3) > 0 ? Time.current.month + (time - 3) : next %>
            <div class="col">
              <h4 class="m-0 text-white">
                <%= @punch_schedules.AM.successed.month_at(month).size %> 次
                (<%= render_this_month_daka_percentage(@punch_schedules.AM.successed.month_at(month), month) %>％)
              </h4>
              <span><%= month %> 月</span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="card prod-p-card background-pattern">
            <div class="card-body">
                <div class="row align-items-center m-b-0">
                    <div class="col">
                      <h6 class="m-b-5">平均上班於</h6>
                      <h3 class="m-b-0"><%= render_time_average(@punch_schedules.successed.AM) %></h3>
                    </div>
                    <div class="col-auto">
                      <i class="material-icons-two-tone text-primary">alarm</i>
                    </div>
                </div>
            </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card prod-p-card bg-primary background-pattern-white">
            <div class="card-body">
                <div class="row align-items-center m-b-0">
                    <div class="col">
                      <h6 class="m-b-5 text-white">平均下班於</h6>
                      <h3 class="m-b-0 text-white"><%= render_time_average(@punch_schedules.successed.PM) %></h3>
                    </div>
                    <div class="col-auto">
                      <i class="material-icons-two-tone text-white">alarm_off</i>
                    </div>
                </div>
            </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card prod-p-card bg-primary background-pattern-white">
            <div class="card-body">
                <div class="row align-items-center m-b-0">
                    <div class="col">
                      <h6 class="m-b-5 text-white">至今成功打卡次數(上/下班)</h6>
                      <h3 class="m-b-0 text-white"><%= @punch_schedules.successed.size %> 次</h3>
                    </div>
                    <div class="col-auto">
                      <i class="material-icons-two-tone text-white">room</i>
                    </div>
                </div>
            </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card prod-p-card background-pattern">
            <div class="card-body">
                <div class="row align-items-center m-b-0">
                    <div class="col">
                      <h6 class="m-b-5">至今取消打卡次數(上/下班)</h6>
                      <h3 class="m-b-0"><%= @punch_schedules.cancel.size %> 次</h3>
                    </div>
                    <div class="col-auto">
                      <i class="material-icons-two-tone text-primary">exit_to_app</i>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <h2>自動打卡記錄<h2>
  </div>
  <div class="card-body">
    <strong><small>系統將於每天 00:30 建立打卡預約單</small></strong>
    <% if @punch_schedules_list.present? %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">時間線</th>
            <th scope="col">日期</th>
            <th scope="col">預計執行時間</th>
            <th scope="col">實際執行時間</th>
            <th scope="col">狀態</th>
            <th scope="col">排程建立時間</th>
            <th scope="col">伺服器回應</th>
          </tr>
        </thead>
        <tbody>
          <% @punch_schedules_list.each do |punch_schedule| %>
            <tr>
              <th scope="row"><%= render_timeline_badge(punch_schedule.time_line) %></th>
              <th scope="row"><%= punch_schedule.date.to_s(:ymd) %></th>
              <th scope="row"><%= Time.zone.at(punch_schedule.schedule_at_unixtime).to_s(:just_time) %></th>
              <th scope="row"><%= render_perform_at_time_string(punch_schedule.perform_at_unixtime) %></th>
              <th scope="row">
                <%= render_status_tag(punch_schedule) %>
                <%= link_to '臨時請假?',  cancel_punch_schedule_path(id: punch_schedule.id), method: "post", class: "ml-2", data: { confirm: "確定取消預約嗎？"} if punch_schedule.pending? %>
              </th>
              <th scope="row"><%= punch_schedule.created_at %></th>
              <th scope="row">
                <% if !punch_schedule.pending? %>
                  <button class="btn btn-sm btn-primary showPopup" data-icon="<%= punch_schedule.status %>" data-response="<%= punch_schedule.response %>">show</button>
                <% end %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @punch_schedules_list, class: "pagination justify-content-center", next_label: "Next", previous_label: "Previous", renderer: CustomPaginateRenderer %>
    <% end %>
  </div>
</div>

<% content_for :js_load do %>
  <script>
    $(function() {
      var options1 = {
        chart: {
          type: 'area',
          height: 85,
          sparkline: {
              enabled: true
          }
        },
        colors: ["#7267EF"],
        stroke: {
          curve: 'smooth',
          width: 2,
        },
        series: [{
          name: "上班於",
          data: <%= render_compression_time_array(@punch_schedules.AM.successed) %>
        }],
        tooltip: {
          fixed: {
              enabled: false
          },
          x: {
              show: false
          },
          y: {
            formatter: function(seriesName) {
              var string = String(seriesName).padStart(4, 0);// var a = '7'; a.padStart(2, 0); ==> '07'
              var hoursString = string.slice(0, 2);
              var secString = string.substr(2, 2);

              return hoursString + ":" + secString
            }
          },
          marker: {
              show: false
          }
        }
      }
      if($("#support-chart").length > 0) {
          new ApexCharts(document.querySelector("#support-chart"), options1).render();
      }
    });
  </script>
<% end %>